# - Try to find Bison
# Once done this will define
#
#  BISON_FOUND - system has Bison
#  BISON_EXECUTABLE - path of the bison executable
#  BISON_VERSION - the version string, like "2.1"
#

FIND_PROGRAM(BISON_EXECUTABLE NAMES bison)

INCLUDE(MacroEnsureVersion)

IF(BISON_EXECUTABLE)
  SET(BISON_FOUND TRUE)
  EXECUTE_PROCESS(
    COMMAND ${BISON_EXECUTABLE} --version
    OUTPUT_VARIABLE _BISON_VERSION
  )
  STRING(REGEX MATCH "[0-9]+\\.[0-9]+" BISON_VERSION ${_BISON_VERSION})
  MACRO_ENSURE_VERSION(2.1 ${BISON_VERSION} _is_GOOD)
  IF(NOT _is_GOOD)
    MESSAGE(FATAL_ERROR "You need Bison >= 2.1 (found ${BISON_VERSION})")
  ENDIF(NOT _is_GOOD)
ENDIF(BISON_EXECUTABLE)

IF(BISON_FOUND)
  IF(NOT BISON_FIND_QUIETLY)
    MESSAGE(STATUS "Found Bison: ${BISON_EXECUTABLE} (${BISON_VERSION})")
  ENDIF(NOT BISON_FIND_QUIETLY)
ELSE(BISON_FOUND)
  IF(BISON_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Bison")
  ENDIF(BISON_FIND_REQUIRED)
ENDIF(BISON_FOUND)
