# - Try to find Flex
# Once done this will define
#
#  FLEX_FOUND - system has Flex
#  FLEX_EXECUTABLE - path of the flex executable
#  FLEX_VERSION - the version string, like "2.5.31"
#

FIND_PROGRAM(FLEX_EXECUTABLE NAMES flex)

INCLUDE(MacroEnsureVersion)

IF(FLEX_EXECUTABLE)
  SET(FLEX_FOUND TRUE)
  EXECUTE_PROCESS(
    COMMAND ${FLEX_EXECUTABLE} --version
    OUTPUT_VARIABLE _FLEX_VERSION
  )
  STRING(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" FLEX_VERSION ${_FLEX_VERSION})
  MACRO_ENSURE_VERSION(2.5.33 ${FLEX_VERSION} _is_GOOD)
  IF(NOT _is_GOOD)
    MESSAGE(FATAL_ERROR "You need Flex >= 2.5.33 (found ${FLEX_VERSION})")
  ENDIF(NOT _is_GOOD)
ENDIF(FLEX_EXECUTABLE)

IF(FLEX_FOUND)
  IF(NOT FLEX_FIND_QUIETLY)
    MESSAGE(STATUS "Found Flex: ${FLEX_EXECUTABLE} (${FLEX_VERSION})")
  ENDIF(NOT FLEX_FIND_QUIETLY)
ELSE(FLEX_FOUND)
  IF(FLEX_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Flex")
  ENDIF(FLEX_FIND_REQUIRED)
ENDIF(FLEX_FOUND)
